name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2, box

      - name: Install dependencies
        run: composer install --no-dev --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Build PHAR
        run: box compile

      - name: Upload PHAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: agentchk.phar
          path: agentchk.phar

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: agentchk.phar
          generate_release_notes: true
